Twigupdatev2
pluginsGLPI/databaseinventory pull request #7
Opened 2023-09-26 13:24 UTC by Lainow

Update of the databaseinventory plugin to switch all html pages to twig.

2023-11-20 10:23 UTC, stonebuzz requested changes
All seems ok for me =)

can you jsut change icon for this (with a computer)

![image](https://github.com/pluginsGLPI/databaseinventory/assets/7335054/20e92b6b-43b5-40f7-a8fd-18816d3e1b8f)

2023-12-05 06:04 UTC, trasher commented
ping?

2024-02-21 08:08 UTC, stonebuzz approved these changes

2024-02-21 11:28 UTC, AdrienClairembault approved these changes
Seems good but a bit hard to read everything.

I think doing one template per PR would be easier to review in the future.

2024-02-21 11:36 UTC, merged